import json
import os
import tempfile
import base64

ASSETS = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public', 'assets')

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
try:
    import qrcode
    from PIL import Image
    HAS_QR = True
except:
    HAS_QR = False

try:
    pdfmetrics.registerFont(TTFont('CG-Light',   os.path.join(ASSETS, 'CormorantGaramond-Light.ttf')))
    pdfmetrics.registerFont(TTFont('CG-LightIt', os.path.join(ASSETS, 'CormorantGaramond-LightItalic.ttf')))
    pdfmetrics.registerFont(TTFont('CG-Regular', os.path.join(ASSETS, 'CormorantGaramond-Regular.ttf')))
except:
    pass

def generate_invoice_pdf(data):
    """Generate SWJ invoice PDF and return path to temp file."""
    
    def fdate(v):
        if not v: return ''
        parts = v.split('-')
        if len(parts)==3: return f"{parts[1]}/{parts[2]}/{parts[0][2:]}"
        return v
    
    def fmt(n): return f"${n:,.2f}"
    
    def wrap(cv, text, font, size, width):
        cv.setFont(font, size)
        words = text.split()
        line, lines = '', []
        for w in words:
            test = (line + ' ' + w).strip()
            if cv.stringWidth(test, font, size) <= width: line = test
            else:
                if line: lines.append(line)
                line = w
        if line: lines.append(line)
        return lines
    
    PW, PH = letter
    ML, MR = 45, 45
    CW = PW - ML - MR
    BLACK = colors.HexColor('#111111')
    GRAY  = colors.HexColor('#555555')
    LGRAY = colors.HexColor('#cccccc')
    
    client     = data['client']
    invnum     = data['invnum']
    address    = data['address']
    invdate    = fdate(data['invdate'])
    startdate  = fdate(data['startdate'])
    baserooms  = data['baserooms']
    extrate    = data['extrate']
    taxrate    = data['taxrate']
    addons     = data['addons']
    promo1     = data['promo1']
    promo2     = data['promo2']
    promo3     = data['promo3']
    paid       = data.get('paid', False)
    paid_date  = data.get('paid_date', '')
    cover_note = data.get('cover_note', '')
    
    addon_total = sum(a['price'] for a in addons)
    subtotal = 2500 + addon_total
    tax = subtotal * taxrate / 100
    grand = subtotal + tax
    
    # Accept payment_url from invoice data (generated by browser) or call Stripe directly
    payment_url = data.get('payment_url') or generate_stripe_link(grand, client, invnum, address)
    qr_path = make_qr_image(payment_url) if payment_url else None
    
    promos = []
    if promo1: promos.append('Monthly Special: Complimentary staging for Kitchen and all Bathrooms.')
    if promo2: promos.append('First-Time Client Bonus: 25 complimentary professional real estate photos included by our preferred photographer.')
    
    safe_client = client.replace(' ','_').replace('/','_').replace(',','')
    safe_addr   = address.replace(' ','_').replace('/','_').replace(',','')[:25]
    import tempfile
    tmpfile = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    tmpfile.close()
    fname = tmpfile.name
    cv = canvas.Canvas(fname, pagesize=letter)
    
    ASSETS = os.path.join(os.path.dirname(__file__), '..', 'public', 'assets')
    LOGO_PATH = os.path.join(ASSETS, 'swj_logo.png')
    SIG_PATH       = '/home/claude/jasmine_signature.png'
    LOGO_WHITE_PATH = os.path.join(ASSETS, 'swj_logo_white.png')
    LOGO_W = 148
    LOGO_H = 85
    
    def draw_header(top_y):
        y = top_y
    
        # Invoice No + Date — top right
        cv.setFont('Helvetica', 8.5)
        cv.setFillColor(BLACK)
        cv.drawRightString(PW-MR, y,      f'Invoice No {invnum}')
        cv.drawRightString(PW-MR, y - 12, invdate)
    
        # Real logo image — top left
        logo_y = y - LOGO_H
        cv.drawImage(LOGO_PATH, ML - 20, logo_y,
                     width=LOGO_W, height=LOGO_H,
                     mask='auto', preserveAspectRatio=True)
    
        # STAGING PROPOSAL — letter-spaced, color #a29c96, centered between logo and invoice block
        logo_right = ML + LOGO_W + 24
        available_w = (PW - MR - 110) - logo_right
        title   = 'STAGING PROPOSAL'
        font_sz = 23
        char_gap = 1.5
        cv.setFont('Helvetica', font_sz)
        title_w = cv.stringWidth(title, 'Helvetica', font_sz) + char_gap * (len(title) - 1)
        title_x = logo_right + (available_w - title_w) / 2
        title_y = y - LOGO_H + 16
        cv.setFillColor(colors.HexColor('#a29c96'))
        tx = title_x
        for ch in title:
            cv.drawString(tx, title_y, ch)
            tx += cv.stringWidth(ch, 'Helvetica', font_sz) + char_gap
    
        # Thin rule under logo/title row
        rule1_y = logo_y - 10
        cv.setStrokeColor(LGRAY); cv.setLineWidth(0.5)
        cv.line(ML, rule1_y, PW-MR, rule1_y)
    
        # Client / Address / Date row
        row_y = rule1_y - 12
        col1, col2, col3 = ML, ML+175, ML+400
    
        cv.setFont('Helvetica', 7.5); cv.setFillColor(colors.HexColor('#888888'))
        cv.drawString(col1, row_y, 'Invoice To:')
        cv.drawString(col2, row_y, 'Property Address:')
        cv.drawString(col3, row_y, 'Project Start Date:')
        row_y -= 12
    
        cv.setFont('Helvetica', 9); cv.setFillColor(BLACK)
        cv.drawString(col1, row_y, client)
    
        addr_lines = wrap(cv, address, 'Helvetica', 9, col3 - col2 - 10)
        ay = row_y
        for al in addr_lines:
            cv.drawString(col2, ay, al); ay -= 11
        cv.drawString(col3, row_y, startdate)
    
        heavy_rule_y = row_y - max(len(addr_lines)*11, 11) - 10
        cv.setStrokeColor(BLACK); cv.setLineWidth(2.0)
        cv.line(ML, heavy_rule_y, PW-MR, heavy_rule_y)
    
        return heavy_rule_y - 14
    
    
    def draw_footer(y):
        cv.setStrokeColor(LGRAY); cv.setLineWidth(0.4)
        cv.line(ML, y, PW-MR, y); y -= 11
        cv.setFont('Helvetica-Bold', 8); cv.setFillColor(BLACK)
        cv.drawString(ML, y, 'Contact'); y -= 11
        cv.setFont('Helvetica', 8); cv.setFillColor(GRAY)
        cv.drawString(ML, y, 'Jasmine Santana'); y -= 11
        cv.drawString(ML, y, 'M: 206-422-5618'); y -= 11
        cv.drawString(ML, y, 'E: info@stylingwithjas.com')
    
    
    def draw_paid_stamp():
        """Overlay a bold diagonal PAID watermark on the current page."""
        cv.saveState()
        cv.setFillColor(colors.HexColor('#cc0000'))
        cv.setStrokeColor(colors.HexColor('#cc0000'))
        cv.setLineWidth(3)
        cv.setFont('Helvetica-Bold', 72)
        cv.setFillAlpha(0.12)
        cv.transform(1, 0.5, 0, 1, 0, 0)
        cv.drawCentredString(PW/2 - 80, PH/2 - 120, 'PAID')
        cv.setFillAlpha(1)
        cv.restoreState()
        # Bold border rect
        cv.saveState()
        cv.setStrokeColor(colors.HexColor('#cc0000'))
        cv.setLineWidth(2.5)
        cv.setStrokeAlpha(0.18)
        stamp_w, stamp_h = 160, 52
        sx = PW/2 - stamp_w/2 + 60
        sy = PH/2 - 60
        cv.roundRect(sx, sy, stamp_w, stamp_h, 6, stroke=1, fill=0)
        cv.setStrokeAlpha(1)
        cv.restoreState()
        # Solid PAID text inside rect
        cv.saveState()
        cv.setFillColor(colors.HexColor('#cc0000'))
        cv.setFont('Helvetica-Bold', 28)
        cv.drawCentredString(PW/2 + 60, PH/2 - 42, 'PAID')
        if paid_date:
            cv.setFont('Helvetica', 9)
            cv.setFillColor(colors.HexColor('#cc0000'))
            cv.drawCentredString(PW/2 + 60, PH/2 - 58, fdate(paid_date))
        cv.restoreState()
    
    def draw_cover_page():
        """Cover page — exact Cormorant Garamond Light 300 matching email template."""
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        try:
            pdfmetrics.registerFont(TTFont('CG-Light',    os.path.join(ASSETS, 'CormorantGaramond-Light.ttf')))
            pdfmetrics.registerFont(TTFont('CG-LightIt',  os.path.join(ASSETS, 'CormorantGaramond-LightItalic.ttf')))
            pdfmetrics.registerFont(TTFont('CG-Regular',  os.path.join(ASSETS, 'CormorantGaramond-Regular.ttf')))
            CG  = 'CG-Light'      # weight 300 — the email uses this everywhere
            CGI = 'CG-LightIt'    # weight 300 italic
        except:
            CG  = 'Helvetica'
            CGI = 'Helvetica-Oblique'
    
        # Exact colors from email CSS
        TAUPE = colors.HexColor('#a29c96')   # --taupe
        DARK  = colors.HexColor('#111111')   # --dark
        WHITE = colors.HexColor('#ffffff')   # --white
        LIGHT = colors.HexColor('#888888')   # --light
        MID   = colors.HexColor('#444444')   # --mid
        RULE  = colors.HexColor('#e8e4e0')   # --border
        BG    = colors.HexColor('#faf9f7')   # --bg
    
        # Full white page
        cv.setFillColor(WHITE)
        cv.rect(0, 0, PW, PH, stroke=0, fill=1)
    
        # ── DARK HEADER — email-header: background #111, padding 40px 48px ──
        header_h = 112
        cv.setFillColor(DARK)
        cv.rect(0, PH - header_h, PW, header_h, stroke=0, fill=1)
    
        # Logo: Cormorant Garamond 36px letter-spacing 4px white (email-logo class)
        # "SWJ" drawn as text with exact letter spacing matching email
        cv.setFillColor(WHITE); cv.setFont(CG, 36)
        logo_text = 'SWJ'
        char_gap = 4.0
        tw = cv.stringWidth(logo_text, CG, 36) + char_gap * (len(logo_text)-1)
        tx = PW/2 - tw/2
        logo_baseline = PH - header_h + (header_h)/2 + 6
        for ch in logo_text:
            cv.drawString(tx, logo_baseline, ch)
            tx += cv.stringWidth(ch, CG, 36) + char_gap
    
        # "STYLING WITH JAS": 10px letter-spacing 3px taupe (email-logo-sub)
        cv.setFillColor(TAUPE); cv.setFont('Helvetica', 8)
        sub = 'STYLING WITH JAS'
        sw = sum(cv.stringWidth(ch,'Helvetica',8)+2.4 for ch in sub)
        sx = PW/2 - sw/2
        for ch in sub:
            cv.drawString(sx, logo_baseline - 16, ch)
            sx += cv.stringWidth(ch,'Helvetica',8)+2.4
    
        # ── HERO — email-hero: background #faf9f7, padding 48px ──
        hero_top = PH - header_h
        hero_h   = 172
        cv.setFillColor(BG)
        cv.rect(0, hero_top - hero_h, PW, hero_h, stroke=0, fill=1)
        cv.setStrokeColor(RULE); cv.setLineWidth(0.5)
        cv.line(0, hero_top - hero_h, PW, hero_top - hero_h)
    
        # email-greeting: CG 13px letter-spacing 2px taupe uppercase
        first_name = client.split()[0] if client else client
        cv.setFillColor(TAUPE); cv.setFont(CG, 13)
        greeting = f'HELLO, {first_name.upper()}'
        gw = cv.stringWidth(greeting, CG, 13)
        # Add extra letter spacing manually
        gx = PW/2 - (gw + 2*len(greeting))/2
        for ch in greeting:
            cv.drawString(gx, hero_top - 30, ch)
            gx += cv.stringWidth(ch, CG, 13) + 2
    
        # email-headline: CG 32px weight 300 color #111 line-height 1.25
        cv.setFillColor(DARK); cv.setFont(CG, 32)
        cv.drawCentredString(PW/2, hero_top - 72, 'Your Staging Proposal')
        cv.drawCentredString(PW/2, hero_top - 112, f'is Ready, {first_name}')
    
        # email-tagline: 13px italic color #888888
        cv.setFillColor(LIGHT); cv.setFont(CGI, 13)
        cv.drawCentredString(PW/2, hero_top - 140, 'Turning every space into a home buyers instantly')
        cv.drawCentredString(PW/2, hero_top - 155, 'connect with.')
    
        # ── BODY — email-body: padding 40px 48px, white background ──
        body_y = hero_top - hero_h - 32
    
        # email-detail-label: 10px letter-spacing 2px uppercase taupe
        cv.setFillColor(TAUPE); cv.setFont('Helvetica', 8)
        cv.drawString(ML, body_y, 'P R O P E R T Y')
        body_y -= 14
    
        # email-address: CG 20px color #111 line-height 1.3
        cv.setFillColor(DARK); cv.setFont(CG, 20)
        addr_parts = address.split(',', 1)
        cv.drawString(ML, body_y, addr_parts[0].strip())
        if len(addr_parts) > 1:
            body_y -= 24
            cv.drawString(ML, body_y, addr_parts[1].strip())
        body_y -= 30
    
        # ── AMOUNT BLOCK — amount-block: bg #faf9f7 padding 28px rounded ──
        box_h = 88; bm = 50
        box_y = body_y - box_h
        cv.setFillColor(BG)
        cv.roundRect(ML + bm, box_y, CW - bm*2, box_h, 8, stroke=0, fill=1)
    
        # amount-label: 10px letter-spacing 2px uppercase #888
        cv.setFillColor(LIGHT); cv.setFont('Helvetica', 8)
        cv.drawCentredString(PW/2, box_y + box_h - 14, 'I N V E S T M E N T   T O T A L')
    
        # amount-value: CG 42px weight 300 letter-spacing 1px
        cv.setFillColor(DARK); cv.setFont(CG, 42)
        cv.drawCentredString(PW/2, box_y + box_h - 52, fmt(grand))
    
        # amount-note: 12px color #888
        cv.setFillColor(LIGHT); cv.setFont('Helvetica', 9)
        cv.drawCentredString(PW/2, box_y + 10,
            f'Invoice No {invnum}  ·  Due by {invdate}')
    
        body_y = box_y - 24
    
        # ── DATES ──
        cv.setStrokeColor(RULE); cv.setLineWidth(0.5)
        cv.line(ML, body_y, PW-MR, body_y); body_y -= 18
    
        lx, rx = ML + CW*0.25, ML + CW*0.75
        cv.setFillColor(LIGHT); cv.setFont('Helvetica', 7.5)
        cv.drawCentredString(lx, body_y, 'PROPOSAL DATE')
        cv.drawCentredString(rx, body_y, 'INSTALLATION DATE')
        body_y -= 16
        cv.setFillColor(DARK); cv.setFont(CG, 14)
        cv.drawCentredString(lx, body_y, invdate)
        cv.drawCentredString(rx, body_y, startdate)
        body_y -= 20
    
        cv.setStrokeColor(RULE); cv.setLineWidth(0.5)
        cv.line(ML, body_y, PW-MR, body_y); body_y -= 18
    
        # ── QUOTE ──
        cv.setFillColor(MID); cv.setFont(CGI, 12)
        cv.drawCentredString(PW/2, body_y,
            '“Design with Intention. Stage with Impact.”')
        body_y -= 15
        cv.setFillColor(TAUPE); cv.setFont('Helvetica', 8)
        cv.drawCentredString(PW/2, body_y,
            '— Jasmine Santana,  Owner & Creative Director')
    
        # ── FOOTER — email-footer: background #111, padding 36px 48px ──
        footer_h = 78
        cv.setFillColor(DARK)
        cv.rect(0, 0, PW, footer_h, stroke=0, fill=1)
    
        # email-footer-logo: CG 22px letter-spacing 3px white
        cv.setFillColor(WHITE); cv.setFont(CG, 22)
        fl_text = 'SWJ'
        fl_gap = 3.0
        fl_w = cv.stringWidth(fl_text, CG, 22) + fl_gap * (len(fl_text)-1)
        fx = PW/2 - fl_w/2
        for ch in fl_text:
            cv.drawString(fx, footer_h - 20, ch)
            fx += cv.stringWidth(ch, CG, 22) + fl_gap
    
        # email-footer-tagline: 11px italic taupe letter-spacing 1px
        cv.setFillColor(TAUPE); cv.setFont(CGI, 10)
        cv.drawCentredString(PW/2, footer_h - 34,
            '“Design with Intention. Stage with Impact.”')
    
        # email-footer-contact: 12px rgba(255,255,255,0.5)
        cv.setFillColor(colors.HexColor('#666666')); cv.setFont('Helvetica', 7.5)
        cv.drawCentredString(PW/2, footer_h - 48,
            'Jasmine Santana  ·  206-422-5618  ·  info@stylingwithjas.com')
    
        # email-footer-fine: 10px rgba(255,255,255,0.3)
        cv.setFillColor(colors.HexColor('#444444')); cv.setFont('Helvetica', 7)
        cv.drawCentredString(PW/2, footer_h - 60,
            'Lux Ventures LLC  ·  © 2026 Styling With Jas')
    
        cv.showPage()
    
    # ── PAGE 1: INVOICE ──
    # Draw cover page if requested
    # Cover page always included
    draw_cover_page()
    
    y = draw_header(775)
    
    qW    = 30
    descW = CW - qW - 90
    
    # Table header — no underline rule
    cv.setFont('Helvetica-Bold', 11); cv.setFillColor(BLACK)
    cv.drawString(ML,           y, 'Quantity')
    cv.drawString(ML + qW + 15, y, 'Description')
    cv.drawRightString(PW-MR,   y, 'Cost')
    y -= 18
    
    def draw_base_row(qty, intro_lines, bold_lines, promo_lines, cost_str):
        global y
        cv.setFillColor(GRAY); cv.setFont('Helvetica', 8.5)
        cv.drawString(ML + 8, y, str(qty))
        ry = y
        for line in intro_lines:
            cv.setFont('Helvetica', 8.5); cv.setFillColor(BLACK)
            cv.drawString(ML + qW + 15, ry, line); ry -= 11
        for line in bold_lines:
            cv.setFont('Helvetica-Bold', 8.5); cv.setFillColor(BLACK)
            cv.drawString(ML + qW + 15, ry, line); ry -= 11
        for line in promo_lines:
            cv.setFont('Helvetica', 8.5); cv.setFillColor(BLACK)
            cv.drawString(ML + qW + 15, ry, line); ry -= 11
        if cost_str:
            cv.setFont('Helvetica', 9)
            cv.drawRightString(PW-MR, y, cost_str)
        all_lines = intro_lines + bold_lines + promo_lines
        row_h = max(len(all_lines)*11, 11) + 12
        y -= row_h
        cv.setStrokeColor(colors.HexColor('#dddddd')); cv.setLineWidth(0.3)
        cv.line(ML, y+4, PW-MR, y+4); y -= 4
    
    def draw_row(qty, lines, cost_str, bold_first_line=False):
        global y
        cv.setFillColor(GRAY); cv.setFont('Helvetica', 8.5)
        cv.drawString(ML + 8, y, str(qty))
        cv.setFillColor(BLACK)
        ry = y
        for i, line in enumerate(lines):
            cv.setFont('Helvetica-Bold' if (bold_first_line and i==0) else 'Helvetica', 8.5)
            cv.drawString(ML + qW + 15, ry, line); ry -= 11
        if cost_str:
            cv.setFont('Helvetica', 9)
            cv.drawRightString(PW-MR, y, cost_str)
        row_h = max(len(lines)*11, 11) + 12
        y -= row_h
        cv.setStrokeColor(colors.HexColor('#dddddd')); cv.setLineWidth(0.3)
        cv.line(ML, y+4, PW-MR, y+4); y -= 4
    
    # ── STRUCTURED BASE ROW ──
    def draw_structured_row(cost_str):
        """Draw the base package row with bullet-point room breakdown."""
        global y
        # Quantity
        cv.setFillColor(GRAY); cv.setFont('Helvetica', 8.5)
        cv.drawString(ML + 8, y, '1')
        cost_y = y  # save for cost string
    
        dx = ML + qW + 15  # description x
        ry = y
    
        # Intro line
        cv.setFont('Helvetica', 8.5); cv.setFillColor(BLACK)
        intro = 'Delivery, setup, pickup, and tear-down, plus up to 45 days of furniture rental.'
        for l in wrap(cv, intro, 'Helvetica', 8.5, descW):
            cv.drawString(dx, ry, l); ry -= 11
        ry -= 4
    
        # Spaces Included header
        cv.setFont('Helvetica-Bold', 8.5); cv.setFillColor(BLACK)
        cv.drawString(dx, ry, 'Spaces Included:'); ry -= 11
    
        # Room list as bullets
        room_list = [r.strip() for r in baserooms.split(',')]
        cv.setFont('Helvetica', 8.5); cv.setFillColor(BLACK)
        for room in room_list:
            cv.drawString(dx, ry, f'\u2022  {room}'); ry -= 11
        ry -= 4
    
        # Closing line
        cv.setFont('Helvetica-Oblique', 8); cv.setFillColor(GRAY)
        closing = 'Each space is thoughtfully designed using curated furnishings to enhance layout, flow, and buyer appeal.'
        for l in wrap(cv, closing, 'Helvetica-Oblique', 8, descW):
            cv.drawString(dx, ry, l); ry -= 10
        ry -= 4
    
        # Promos
        if promos:
            cv.setFont('Helvetica-Bold', 8.5); cv.setFillColor(BLACK)
            label = 'Two promotions have been applied:' if len(promos)>1 else 'Promotion has been applied:'
            cv.drawString(dx, ry, label); ry -= 11
            cv.setFont('Helvetica', 8.5)
            for p in promos:
                for l in wrap(cv, '\u2022  '+p, 'Helvetica', 8.5, descW-10):
                    cv.drawString(dx, ry, l); ry -= 11
            ry -= 4
    
        # Cost at top right
        if cost_str:
            cv.setFont('Helvetica', 9); cv.setFillColor(BLACK)
            cv.drawRightString(PW-MR, cost_y, cost_str)
    
        row_h = cost_y - ry + 12
        y -= row_h
        cv.setStrokeColor(colors.HexColor('#dddddd')); cv.setLineWidth(0.3)
        cv.line(ML, y+4, PW-MR, y+4); y -= 4
    
    draw_structured_row(fmt(2500))
    
    # ── STRUCTURED ADDON ROWS ──
    def draw_addon_structured(desc_raw, cost_str):
        """Parse addon description and render as structured bullets."""
        global y
        cv.setFillColor(GRAY); cv.setFont('Helvetica', 8.5)
        cv.drawString(ML + 8, y, '1')
        cost_y = y
        dx = ML + qW + 15
        ry = y
    
        # Parse: "Primary bedroom (Queen) — Medium: scope..." or "Room: scope..." or custom
        # Header shown to client = room name only (strip bed size and room size)
        # Scope = everything after the first ': '
        import re
        if ': ' in desc_raw:
            raw_header, scope_part = desc_raw.split(': ', 1)
        else:
            raw_header = desc_raw
            scope_part = ''
    
        # Strip bed size "(Queen)" and size tier "— Medium" from header
        # Keep only the room name e.g. "Primary bedroom" or custom label
        clean_header = re.sub(r'\s*\([^)]+\)', '', raw_header)   # remove (Queen), (King) etc
        clean_header = re.sub(r'\s*—.*$', '', clean_header)         # remove — Medium, — Small etc
        clean_header = clean_header.strip()
    
        # Bold header — room name only
        cv.setFont('Helvetica-Bold', 8.5); cv.setFillColor(BLACK)
        for l in wrap(cv, clean_header, 'Helvetica-Bold', 8.5, descW):
            cv.drawString(dx, ry, l); ry -= 11
    
        # Render scope as structured bullets if it contains comma-separated items
        # or just as a readable paragraph broken into bullets
        if scope_part:
            ry -= 3
            # Split scope into bullet points by sentence or comma
            import re
            # Split on '. ' or ', ' to create bullets
            raw_items = re.split(r',\s*(?=[A-Z])|(?<=\.)\s+(?=[A-Z])', scope_part)
            if len(raw_items) > 1:
                cv.setFont('Helvetica', 8.5); cv.setFillColor(BLACK)
                for item in raw_items:
                    item = item.strip().rstrip('.')
                    if item:
                        for l in wrap(cv, '\u2022  '+item, 'Helvetica', 8.5, descW-10):
                            cv.drawString(dx, ry, l); ry -= 11
            else:
                # Wrap as paragraph
                cv.setFont('Helvetica', 8.5); cv.setFillColor(BLACK)
                for l in wrap(cv, scope_part, 'Helvetica', 8.5, descW):
                    cv.drawString(dx, ry, l); ry -= 11
    
        if cost_str:
            cv.setFont('Helvetica', 9); cv.setFillColor(BLACK)
            cv.drawRightString(PW-MR, cost_y, cost_str)
    
        row_h = cost_y - ry + 12
        y -= row_h
        cv.setStrokeColor(colors.HexColor('#dddddd')); cv.setLineWidth(0.3)
        cv.line(ML, y+4, PW-MR, y+4); y -= 4
    
    for a in addons:
        draw_addon_structured(a['desc'], fmt(a['price']))
    
    if promo3:
        photo = ("Photography Services (Included at No Additional Charge): Up to 25 professional real estate "
                 "photos are included as a complimentary service. Photography will be done with Jasmine's preferred "
                 "photographer. Drone photography may be provided upon client request, when permitted, and if the "
                 "property is not located in a restricted no-fly zone. Photos will be scheduled at the photographer's "
                 "convenience, typically the following day after staging. Please allow up to 24-26 hours after the "
                 "photography session for delivery of final images.")
        draw_row(1, wrap(cv, photo, 'Helvetica', 8.5, descW), '-------')
    
    y -= 8
    
    # Totals
    cv.setFont('Helvetica', 9); cv.setFillColor(GRAY)
    cv.drawString(PW-MR-120, y, 'Subtotal:');                cv.drawRightString(PW-MR, y, fmt(subtotal)); y -= 13
    cv.drawString(PW-MR-120, y, f'Taxes ({taxrate:.2f}%):'); cv.drawRightString(PW-MR, y, fmt(tax));      y -= 5
    cv.setStrokeColor(BLACK); cv.setLineWidth(0.8)
    cv.line(PW-MR-130, y, PW-MR, y); y -= 13
    cv.setFont('Helvetica-Bold', 10); cv.setFillColor(BLACK)
    cv.drawString(PW-MR-120, y, 'Grand Total:');             cv.drawRightString(PW-MR, y, fmt(grand));    y -= 34
    
    # Extension italic note
    cv.setFont('Helvetica-Oblique', 8); cv.setFillColor(GRAY)
    ext_note = (f"Invoice covers up to 45 days of furniture rental. After 45 days, rental "
                f"may be extended at {fmt(extrate)} per 30-day period, billed separately.")
    note_lines = wrap(cv, ext_note, 'Helvetica-Oblique', 8, CW * 0.60)
    note_x = ML + CW * 0.18
    for l in note_lines:
        cv.drawString(note_x, y, l); y -= 11
    
    y -= 18
    
    # ── PAYMENT SECTION ──
    if payment_url or True:
        cv.setStrokeColor(LGRAY); cv.setLineWidth(0.4)
        cv.line(ML, y, PW-MR, y); y -= 12
    
        if payment_url:
            # QR code — right side
            qr_size = 58
            qr_x = PW - MR - qr_size
            qr_y = y - qr_size
            if qr_path:
                cv.drawImage(qr_path, qr_x, qr_y,
                             width=qr_size, height=qr_size, preserveAspectRatio=True)
    
            # Payment text — left side
            cv.setFont('Helvetica-Bold', 8.5); cv.setFillColor(BLACK)
            cv.drawString(ML, y, 'Pay Online'); y -= 12
            cv.setFont('Helvetica', 7.5); cv.setFillColor(GRAY)
            cv.drawString(ML, y, 'Scan to pay with credit card, debit card, or Apple Pay:'); y -= 11
    
            # Print URL — break into chunks if too long
            cv.setFont('Helvetica', 7.5); cv.setFillColor(colors.HexColor('#1a73e8'))
            max_url_w = qr_x - ML - 10
            url_lines = []
            remaining = payment_url
            while cv.stringWidth(remaining, 'Helvetica', 7.5) > max_url_w and len(remaining) > 20:
                split = int(len(remaining) * max_url_w / cv.stringWidth(remaining, 'Helvetica', 7.5)) - 1
                url_lines.append(remaining[:split])
                remaining = remaining[split:]
            url_lines.append(remaining)
            for ul in url_lines:
                cv.drawString(ML, y, ul); y -= 10
    
            y = min(y, qr_y) - 10
        else:
            cv.setFont('Helvetica', 8); cv.setFillColor(GRAY)
            cv.drawString(ML, y, 'Payment accepted via Venmo, Cashier Check, Credit/Debit Cards, or Cash.'); y -= 14
    
        if qr_path:
            try: os.unlink(qr_path)
            except: pass
    
    draw_footer(y)
    
    
    # PAID stamp overlay on page 1
    if paid:
        draw_paid_stamp()
    
    # ── PAGE 2: TERMS & CONDITIONS + SIGNATURES ──
    cv.showPage()
    y = draw_header(775)
    
    def tc_section(title, items):
        global y
        cv.setFont('Helvetica-Bold', 8.5); cv.setFillColor(BLACK)
        cv.drawString(ML, y, title); y -= 12
        cv.setFont('Helvetica', 8); cv.setFillColor(colors.HexColor('#333333'))
        for item in items:
            for l in wrap(cv, item, 'Helvetica', 8, CW):
                cv.drawString(ML, y, l); y -= 10
        y -= 6
    
    tc_section('Production Timeline', [
        'Installation and styling may require up to 48 hours to complete the final presentation.',
        'ETA will be provided on the day of installation if needed.',
        'Installation is scheduled within a staging window and may occur at varying times throughout the day. A defined start or completion time is not guaranteed.',
        'Final staging presentation is delivered upon completion of installation.',
    ])
    tc_section('Payment & Rental Terms', [
        'Full payment is due 48 hours prior to staging installation day.',
        'Staging will not be scheduled until full payment is received.',
        'Invoice covers up to 45 days of furniture rental from installation date.',
        f'After 45 days, rental may be extended at {fmt(extrate)} per additional 30-day period, billed separately.',
        'Cancellations within 72 hours of installation may incur a cancellation fee of $700 to cover labor and logistics.',
    ])
    tc_section('Client Responsibility', [
        'Client assumes responsibility for all furnishings once installed.',
        'Styling With Jas is not responsible for damage, loss, or theft of staging items.',
        'Staged items are not to be relocated, altered, or removed without prior approval.',
        'Client is responsible for maintaining property condition throughout the staging period.',
    ])
    tc_section('Preparation & Access Requirements', [
        'Property must be cleaned and photo-ready prior to installation.',
        'Property must be free of contractors or other vendors during scheduled staging unless pre-approved.',
        'Driveway and entry access must be clear for unloading and installation.',
        'Active utilities (water, electricity, and HVAC) must be operational at time of staging.',
        'Seller presence during installation is permitted; however, installation must proceed without interruption to ensure efficiency and cohesive final presentation. Design feedback is to be provided after installation is complete.',
    ])
    tc_section('Scope & Adjustment Terms', [
        'Scope includes initial design, installation, and one post-install adjustment visit if requested within 48 hours of installation.',
        'Additional adjustment visits are billed at $250 per visit.',
        'Any requested changes outside the defined scope require written approval and may incur additional fees.',
        'Staging does not include cleaning, repairs, patching, painting, or relocation of seller-owned furnishings unless agreed in writing.',
        'Extensions beyond the included rental period are subject to availability and additional rental fees.',
        'Design selections and placement are at the discretion of the stager to ensure cohesive presentation and market readiness.',
        'All staging selections are curated to enhance marketability and may not reflect personal design preferences.',
        'Final staging approval is deemed accepted once installation is completed and property photography has commenced.',
    ])
    tc_section('Marketing Rights', [
        'Styling With Jas reserves the right to photograph staged spaces for marketing, promotional, and portfolio purposes.',
    ])
    
    y -= 8
    
    # Photography Addendum (only if promo3)
    if promo3:
        cv.setStrokeColor(LGRAY); cv.setLineWidth(0.4)
        cv.line(ML, y, PW-MR, y); y -= 12
        cv.setFont('Helvetica-Bold', 8.5); cv.setFillColor(BLACK)
        cv.drawString(ML, y, 'Photography Services Addendum'); y -= 12
        cv.setFont('Helvetica', 8); cv.setFillColor(colors.HexColor('#333333'))
        disclaimer = ("Up to 25 professional real estate photos are included as a complimentary service. "
                      "Photography will be done with Jasmine's preferred photographer. Drone photography may be "
                      "provided upon client request, when permitted, and if the property is not located in a "
                      "restricted no-fly zone. Photos will be scheduled at the photographer's convenience, typically "
                      "the following day after staging. Please allow up to 24-26 hours after the photography session "
                      "for delivery of final images.")
        for l in wrap(cv, disclaimer, 'Helvetica', 8, CW):
            cv.drawString(ML, y, l); y -= 10
        y -= 6
        cv.setFont('Helvetica', 8.5); cv.setFillColor(BLACK)
        cv.rect(ML, y - 1, 9, 9, stroke=1, fill=0)
        cv.drawString(ML + 14, y + 7, 'Client requests drone photography (if available and permitted)')
        y -= 18
        cv.setFont('Helvetica', 8); cv.setFillColor(colors.HexColor('#333333'))
        cv.drawString(ML, y, 'Client Initials:')
        cv.setStrokeColor(colors.HexColor('#999999')); cv.setLineWidth(0.5)
        cv.line(ML + 80, y + 2, ML + 180, y + 2)
        y -= 16
    
    # Signatures
    cv.setStrokeColor(LGRAY); cv.setLineWidth(0.4)
    cv.line(ML, y, PW-MR, y); y -= 14
    
    cv.setFont('Helvetica-Bold', 8.5); cv.setFillColor(BLACK)
    cv.drawCentredString(PW/2, y, 'Acceptance of Proposal'); y -= 10
    cv.setFont('Helvetica', 7.5); cv.setFillColor(colors.HexColor('#444444'))
    cv.drawCentredString(PW/2, y, 'By signing below, both parties confirm they have read, understood, and agree to all terms, pricing, and conditions above.')
    y -= 22
    
    sig_w = CW * 0.55
    cv.setFont('Helvetica', 8); cv.setFillColor(colors.HexColor('#333333'))
    cv.drawString(ML, y, 'Client Signature:')
    cv.setStrokeColor(colors.HexColor('#999999')); cv.setLineWidth(0.5)
    cv.line(ML+90, y+2, ML+sig_w, y+2); y -= 12
    cv.drawString(ML, y, 'Printed Name:')
    cv.line(ML+75, y+2, ML+sig_w, y+2); y -= 12
    cv.drawString(ML, y, 'Date:')
    cv.line(ML+30, y+2, ML+sig_w, y+2); y -= 24
    
    cv.setFont('Helvetica-Bold', 8); cv.setFillColor(BLACK)
    cv.drawString(ML, y, 'Styling With Jas'); y -= 11
    cv.setFont('Helvetica', 8); cv.setFillColor(colors.HexColor('#333333'))
    cv.drawString(ML, y, 'Lux Ventures LLC'); y -= 11
    cv.drawString(ML, y, 'Jasmine Santana'); y -= 11
    cv.drawString(ML, y, 'Owner & Creative Director'); y -= 22
    
    # Signature label
    cv.drawString(ML, y, 'Signature:')
    
    # Signature image — sits right on the signature line
    sig_img_w = 70
    sig_img_h = int(649 * sig_img_w / 1154)   # proportional to new signature
    # Draw image aligned to the text baseline
    cv.drawImage(SIG_PATH, ML + 55, y - 4,
                 width=sig_img_w, height=sig_img_h,
                 mask='auto', preserveAspectRatio=True)
    y -= 18   # move down past the signature
    
    # Date — one clean line below signature
    cv.setFont('Helvetica', 8); cv.setFillColor(colors.HexColor('#333333'))
    cv.drawString(ML, y, 'Date:')
    cv.drawString(ML + 30, y, invdate)
    y -= 30   # generous gap — no footer on page 2
    
    # PAID stamp on page 2 as well
    if paid:
        draw_paid_stamp()
    
    cv.save()
    print(fname)

    return fname


def handler(request):
    if request.method == 'OPTIONS':
        return Response('', headers={
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
        })

    if request.method != 'POST':
        return Response(json.dumps({'error': 'Method not allowed'}), status=405)

    try:
        data = json.loads(request.body)
    except:
        return Response(json.dumps({'error': 'Invalid JSON'}), status=400)

    try:
        pdf_path = generate_invoice_pdf(data)
        with open(pdf_path, 'rb') as f:
            pdf_bytes = f.read()
        os.unlink(pdf_path)

        client_safe = data.get('client','').replace(' ','_')
        invnum = data.get('invnum','invoice')
        filename = f"SWJ_{client_safe}_{invnum}.pdf"

        return Response(
            pdf_bytes,
            headers={
                'Content-Type': 'application/pdf',
                'Content-Disposition': f'attachment; filename="{filename}"',
                'Access-Control-Allow-Origin': '*',
            }
        )
    except Exception as e:
        import traceback
        return Response(
            json.dumps({'error': str(e), 'trace': traceback.format_exc()}),
            status=500,
            headers={'Content-Type': 'application/json'}
        )
